import 'package:hive/hive.dart';

part 'receipts.g.dart'; // This file will be generated by Hive generator

@HiveType(typeId: 0)
class Expense extends HiveObject {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String date;

  @HiveField(2)
  final double value;

  Expense({required this.id, required this.date, required this.value});
}
